version: '3'
services:
  app:
    image: app
    ports:
      - 8034:8034
  frontContainer:
    image: frontapp
    ports:
      - 4200:4200
  mySQLContainer:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=default
      - MYSQL_DATABASE=employee_management_system
    ports:
      - 3306:3306